### ISSUE TITLE
Hidden matcher not hiding controls initially

### ISSUE THREAD

**Issue by drkhannah** [udos86/ng-dynamic-forms#1095]
## I'm submitting a

<pre><code>
[ ] Bug / Regression
[ ] Feature Request / Proposal
</code></pre>

## I'm using

<pre><code>
NG Dynamic Forms Version: `12.0`

[ ] Basic UI
[ ] Bootstrap UI  
[ ] Foundation UI
[ ] Ionic UI
[ ] Kendo UI
[ ] Material  
[ ] NG Bootstrap
[x ] Prime NG
</code></pre>

## Description
I'm using relations to hide a input when a checkbox is checked, it works when checking and unchecking the box, but the input is not hidden on initial creation of the form, i have to check and uncheck the box once to get it to start working

also on initial form creation, the box is unchecked, if i click the input that should be hidden without checking the box, the input hides

this used to work before upgrading to version 12.0

**Comment by drkhannah** [comment]
Bump ^ this is still an issue for me, it seems when the lib first creates a form it doesn't add the `hidden` attribute for groups that should be hidden based on a relation that hides it, but after interacting with the form the first time then those hidden relations work

**Comment by begandroide** [comment]
hello @drkhannah Im using this library and facing the same issue, the hidden matcher not hide control until you click on it; @udos86 please help us!

As a workaround you can place the attribute `hidden: true` to model properties of your dynamic control when values are empty.

**Comment by drkhannah** [comment]
I fixed this by calling these two methods after creating the form
ChangeDetetctorRef.detectChanges()
DynamicFormService.detectChanges()

**Comment by begandroide** [comment]
you has a special detection strategy? Im using this and still not working: 
```ts
contructor(private dynamicFormService: DynamicFormService, private detectorChanges: ChangeDetectorRef) { }

createFromJson(json: string) {
    const formModel = this.formDynamicService.fromJSON(this.form.value.json);
    this.formGroups = { _formGroup: this.formDynamicService.createFormGroup(formModel), _formModel: formModel} ;
    this.dynamicFormService.detectChanges();
    this.detectorChanges.detectChanges();
}
```

**Comment by drkhannah** [comment]
Call
this.detectorChanges.detectChanges()
this.dynamicFormService.detectChanges()

In that exact order

**Comment by begandroide** [comment]
@drkhannah thank you very much, this worked for me! 😃

**Comment by drkhannah** [comment]
Glad to hear
